// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel MipmapKernel

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D readSourceTx;
RWTexture2D<float4> Result;
float Resolution;

[numthreads(8,8,1)]
void MipmapKernel (uint3 id : SV_DispatchThreadID)
{
    float2 tc = id.xy / Resolution;

    Result[id.xy] = float4(tc, 0, 1);
}
